import Navigation from "@/app/components/Navigation";
import "./globals.css";
import { Montserrat } from "next/font/google";
import styles from "../styles/body.module.css";

const montserrat = Montserrat({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} bg-gray-800 text-white`}>
        <header className="">
          <Navigation />
        </header>

        <div className={styles.background}>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
        </div>
        <div className="p-5">{children}</div>
      </body>
    </html>
  );
}
